### ISSUE TITLE
[Bug]: Alpine Expression Error: pgToggleable is not defined

### ISSUE THREAD

**Issue by JACarrasco7** [Power-Components/livewire-powergrid#959]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

![toggle](https://user-images.githubusercontent.com/45757951/236413525-c294933a-7414-48d1-9376-1598e339af8c.PNG)

### PHP Version

8.0.2

### PowerGrid

4.4.2

### Laravel

9.52.7

### Livewire

2.12.3

### Alpine JS

3.12.0

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When I put a toggleable input it doesn't work and I get the following error in the console

![toggle](https://user-images.githubusercontent.com/45757951/236414148-da92fbf7-5d99-4e1f-a51a-53b0918ce710.PNG)

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;
use PowerComponents\LivewirePowerGrid\Rules\{Rule, RuleActions};
use PowerComponents\LivewirePowerGrid\Traits\{ActionButton, WithExport};
use PowerComponents\LivewirePowerGrid\Filters\Filter;
use PowerComponents\LivewirePowerGrid\{Button, Column, Exportable, Footer, Header, PowerGrid, PowerGridComponent, PowerGridEloquent};

final class UserTable extends PowerGridComponent
{
    use ActionButton;
    use WithExport;

    protected function getListeners()
    {
        return array_merge(
            parent::getListeners(),
            [
                'datasource',
                'createUser',
                'deleteUserConfirm',
                'deleteUser'
            ]
        );
    }

    /*
    |--------------------------------------------------------------------------
    |  Features Setup
    |--------------------------------------------------------------------------
    | Setup Table's general features
    |
    */
    public function setUp(): array
    {
        $this->showCheckBox();

        return [
            Header::make()->showSearchInput(),
            Footer::make()
                ->showPerPage()
                ->showRecordCount(),
        ];
    }

    /*
    |--------------------------------------------------------------------------
    |  Datasource
    |--------------------------------------------------------------------------
    | Provides data to your Table using a Model or Collection
    |
    */

    /**
     * PowerGrid datasource.
     *
     * @return Builder<\App\Models\User>
     */
    public function datasource(): Builder
    {
        return User::query();
    }

    /*
    |--------------------------------------------------------------------------
    |  Relationship Search
    |--------------------------------------------------------------------------
    | Configure here relationships to be used by the Search and Table Filters.
    |
    */

    /**
     * Relationship search.
     *
     * @return array<string, array<int, string>>
     */
    public function relationSearch(): array
    {
        return [];
    }

    /*
    |--------------------------------------------------------------------------
    |  Add Column
    |--------------------------------------------------------------------------
    | Make Datasource fields available to be used as columns.
    | You can pass a closure to transform/modify the data.
    |
    | ❗ IMPORTANT: When using closures, you must escape any value coming from
    |    the database using the `e()` Laravel Helper function.
    |
    */
    public function addColumns(): PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('id')
            ->addColumn('username')
            ->addColumn('name', function (User $model) {
                return strtolower(e($model->user_data->name));
            })
            ->addColumn('surnames', function (User $model) {
                return strtolower(e($model->user_data->surnames));
            })
            ->addColumn('email')
            ->addColumn('phone', function (User $model) {
                return strtolower(e($model->user_data->phone));
            })
            ->addColumn('role', function (User $model) {
                return __($model->getRoleNames()[0]);
            });
    }

    /*
    |--------------------------------------------------------------------------
    |  Include Columns
    |--------------------------------------------------------------------------
    | Include the columns added columns, making them visible on the Table.
    | Each column can be configured with properties, filters, actions...
    |
    */

    /**
     * PowerGrid Columns.
     *
     * @return array<int, Column>
     */
    public function columns(): array
    {
        return [
            Column::make(__('Username'), 'username')
                ->sortable()
                ->searchable(),

            Column::make(__('Name'), 'name')
                ->sortable()
                ->searchable(),

            Column::make(__('Surnames'), 'surnames')
                ->sortable()
                ->searchable(),

            Column::make('Email', 'email')
                ->sortable()
                ->searchable(),

            Column::make(__('Phone'), 'phone')
                ->sortable()
                ->searchable(),

            Column::make('Rol', 'role')
                ->sortable()
                ->searchable(),

            Column::make('Estado', 'status')
                ->toggleable(true, 'yes', 'no'),

        ];
    }

    /**
     * PowerGrid Filters.
     *
     * @return array<int, Filter>
     */
    public function filters(): array
    {
        return [
            Filter::inputText('name')->operators(['contains']),
            Filter::inputText('email')->operators(['contains']),
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Actions Method
    |--------------------------------------------------------------------------
    | Enable the method below only if the Routes below are defined in your app.
    |
    */

    /**
     * PowerGrid User Action Buttons.
     *
     * @return array<int, Button>
     */

    public function header(): array
    {

        return [
            Button::make('create', 'Crear usuario')
                ->class('Button js-open-button bg-indigo-600 cursor-pointer text-white px-3 rounded text-sm leading-10 hover:bg-indigo-800')
                ->openModal('user-modal', [])
        ];
    }


    public function actions(): array
    {
        return [
            Button::make('view', '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          </svg>
          ')
                ->class('Button cursor-pointer px-3 py-2.5 m-1 rounded text-sm hover:bg-indigo-400 hover:text-white active:bg-indigo-500')
                ->openModal('user-modal', ['user' => 'user']),

            Button::add('edit')
                ->caption('<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
          </svg>
          ')->class('Button js-open-button cursor-pointer px-3 py-2.5 m-1 rounded text-sm hover:bg-amber-400 hover:text-white active:bg-amber-500')
                ->openModal('user-modal', ['user' => 'id']),

            Button::make('delete', '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
              </svg>
              ')
                ->class('Button cursor-pointer px-3 py-2.5 m-1 rounded text-sm hover:bg-red-400 hover:text-white active:bg-red-500')
                ->emit('deleteUserConfirm', ['id' => 'id'])
        ];
    }


    /*
    |--------------------------------------------------------------------------
    | Actions Rules
    |--------------------------------------------------------------------------
    | Enable the method below to configure Rules for your Table and Action Buttons.
    |
    */

    /**
     * PowerGrid User Action Rules.
     *
     * @return array<int, RuleActions>
     */

    public function actionRules(): array
    {
        return [
            Rule::button('edit')
                ->when(fn ($user) => $user->id === Auth::user()->id || strtolower($user->getRoleNames()[0]) == strtolower(config('constants.ROLE.ADMINISTRATOR.NAME')))
                ->hide(),

            Rule::button('delete')
                ->when(fn ($user) => $user->id === Auth::user()->id || strtolower($user->getRoleNames()[0]) == strtolower(config('constants.ROLE.ADMINISTRATOR.NAME')))
                ->hide(),
        ];
    }

    public function onUpdatedToggleable(string $id, string $field, string $value): void
    {
        User::query()->find($id)->update([
            $field => $value,
        ]);
    }
}
```

**Comment by rosolovsky** [comment]
Can i see app.js ?

**Comment by JACarrasco7** [comment]
La importacion de Alpine esta comentada ya que tengo la llamada en el app.blade.php
Ya he probado a descomentarla y comentar la de app.blade.php pero sigue igual

------------------------------------------ app.js---------------------------------------------------------------------

// import Alpine from "alpinejs";

// window.Alpine = Alpine;

import "./../../vendor/power-components/livewire-powergrid/dist/powergrid";
import "./../../vendor/power-components/livewire-powergrid/dist/powergrid.css";

// Alpine.start();

ChangeColorTheme();

function ChangeColorTheme() {
    // It's best to inline this in `head` to avoid FOUC (flash of unstyled content) when changing pages or themes
    if (
        localStorage.getItem("color-theme") === "dark" ||
        (!("color-theme" in localStorage) &&
            window.matchMedia("(prefers-color-scheme: dark)").matches)
    ) {
        document.documentElement.classList.add("dark");
    } else {
        document.documentElement.classList.remove("dark");
    }

    //Change theme color for button

    var themeToggleDarkIcon = document.getElementById("theme-toggle-dark-icon");
    var themeToggleLightIcon = document.getElementById(
        "theme-toggle-light-icon"
    );

    // Change the icons inside the button based on previous settings
    if (
        localStorage.getItem("color-theme") === "dark" ||
        (!("color-theme" in localStorage) &&
            window.matchMedia("(prefers-color-scheme: dark)").matches)
    ) {
        themeToggleLightIcon.classList.remove("hidden");
    } else {
        themeToggleDarkIcon.classList.remove("hidden");
    }

    var themeToggleBtn = document.getElementById("theme-toggle");

    themeToggleBtn.addEventListener("click", function () {
        // toggle icons inside button
        themeToggleDarkIcon.classList.toggle("hidden");
        themeToggleLightIcon.classList.toggle("hidden");

        // if set via local storage previously
        if (localStorage.getItem("color-theme")) {
            if (localStorage.getItem("color-theme") === "light") {
                document.documentElement.classList.add("dark");
                localStorage.setItem("color-theme", "dark");
            } else {
                document.documentElement.classList.remove("dark");
                localStorage.setItem("color-theme", "light");
            }

            // if NOT set via local storage previously
        } else {
            if (document.documentElement.classList.contains("dark")) {
                document.documentElement.classList.remove("dark");
                localStorage.setItem("color-theme", "light");
            } else {
                document.documentElement.classList.add("dark");
                localStorage.setItem("color-theme", "dark");
            }
        }
    });
}

// SWEET ALERTS

Livewire.on("AlertConfirm", (data) => {
    Swal.fire({
        title: "¿Estás seguro?",
        html: data.text,
        icon: "warning",
        showCancelButton: true,
        confirmButtonText: "Sí, eliminar!",
        cancelButtonText: "No, cancelar!",
        confirmButtonColor: "#3C5485",
        cancelButtonColor: "#d33",
    }).then((result) => {
        if (result.isConfirmed) {
            Livewire.emitTo(data.table, data.method, data.id);
        }
    });
});

Livewire.on("AlertOk", (data) => {
    Swal.fire(data.title, data.text, "success");

    if (data.table)
        setTimeout(function () {
            $(".js-close-button").trigger("click");
            Livewire.emitTo("user-table", "datasource");
        }, 1000);
});

Livewire.on("AlertFail", (data) => {
    Swal.fire(data.title, data.text, "error");

    if (data.table)
        setTimeout(function () {
            $(".js-close-button").trigger("click");
            Livewire.emitTo("user-table", "datasource");
        }, 1000);
});

------------------------------------------ app.js---------------------------------------------------------------------

------------------------------------------ app.blade.php--------------------------------------------------------------------

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

    
    @vite('resources/css/app.css')
    @livewireStyles
    @wireUiScripts
    <script src="//unpkg.com/alpinejs" defer></script>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
</head>

<body class="font-sans antialiased">
    <div class="min-h-screen bg-gray-100 dark:bg-gray-900">
        @include('layouts.navigation')

        
        @if (isset($header))
            <header class="bg-white dark:bg-gray-800 shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>
        @endif

        
        <main>
            {{ $slot }}
        </main>
    </div>
    @livewire('livewire-ui-modal')
    @livewireScripts
</body>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@vite('resources/js/app.js')

</html>


------------------------------------------ app.blade.php--------------------------------------------------------------------

**Comment by rosolovsky** [comment]
Use @vite(['resources/css/app.css', 'resources/js/app.js']) in head section app.blade.php !!!

Most likely, you have a problem with scripts and js libraries or with the order of their connection. Because I have no problems with Powergrid. I recommend connecting Alpine js as a module in app.js and also abandoning the use of the jQuery library.

**Comment by JACarrasco7** [comment]
I created a new project and it still doesn't work. The versions with the same as in the previous one and are the requirements that powergrid requires.


---- app.blade.php----

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        
        @vite(['resources/css/app.css', 'resources/js/app.js'])
         @livewireStyles
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            
            <main>
                {{ $slot }}
            </main>
        </div>
          @livewireScripts
    </body>
</html>


---- app.blade.php ----


---- app.js ----

import "./bootstrap";

import Alpine from "alpinejs";
import flatpickr from "flatpickr";

window.Alpine = Alpine;
window.flatpickr = flatpickr;

import "./../../node_modules/flatpickr/dist/flatpickr.min.css";
import "./../../vendor/power-components/livewire-powergrid/dist/powergrid";
import "./../../vendor/power-components/livewire-powergrid/dist/powergrid.css";

Alpine.start();


---- app.js ----

---- UserTable.php ----

<?php

namespace App\Http\Livewire;

use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Builder;
use PowerComponents\LivewirePowerGrid\Rules\{Rule, RuleActions};
use PowerComponents\LivewirePowerGrid\Traits\{ActionButton, WithExport};
use PowerComponents\LivewirePowerGrid\Filters\Filter;
use PowerComponents\LivewirePowerGrid\{Button, Column, Exportable, Footer, Header, PowerGrid, PowerGridComponent, PowerGridEloquent};

final class UserTable extends PowerGridComponent
{
    use ActionButton;
    use WithExport;

    /*
    |--------------------------------------------------------------------------
    |  Features Setup
    |--------------------------------------------------------------------------
    | Setup Table's general features
    |
    */
    public function setUp(): array
    {
        $this->showCheckBox();

        return [
            Exportable::make('export')
                ->striped()
                ->type(Exportable::TYPE_XLS, Exportable::TYPE_CSV),
            Header::make()->showSearchInput(),
            Footer::make()
                ->showPerPage()
                ->showRecordCount(),
        ];
    }

    /*
    |--------------------------------------------------------------------------
    |  Datasource
    |--------------------------------------------------------------------------
    | Provides data to your Table using a Model or Collection
    |
    */

    /**
     * PowerGrid datasource.
     *
     * @return Builder<\App\Models\User>
     */
    public function datasource(): Builder
    {
        return User::query();
    }

    /*
    |--------------------------------------------------------------------------
    |  Relationship Search
    |--------------------------------------------------------------------------
    | Configure here relationships to be used by the Search and Table Filters.
    |
    */

    /**
     * Relationship search.
     *
     * @return array<string, array<int, string>>
     */
    public function relationSearch(): array
    {
        return [];
    }

    /*
    |--------------------------------------------------------------------------
    |  Add Column
    |--------------------------------------------------------------------------
    | Make Datasource fields available to be used as columns.
    | You can pass a closure to transform/modify the data.
    |
    | ❗ IMPORTANT: When using closures, you must escape any value coming from
    |    the database using the `e()` Laravel Helper function.
    |
    */
    public function addColumns(): PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('id')
            ->addColumn('name')

            /** Example of custom column using a closure **/
            ->addColumn('name_lower', fn (User $model) => strtolower(e($model->name)))

            ->addColumn('email')
            ->addColumn('status')
            ->addColumn('created_at_formatted', fn (User $model) => Carbon::parse($model->created_at)->format('d/m/Y H:i:s'));
    }

    /*
    |--------------------------------------------------------------------------
    |  Include Columns
    |--------------------------------------------------------------------------
    | Include the columns added columns, making them visible on the Table.
    | Each column can be configured with properties, filters, actions...
    |
    */

    /**
     * PowerGrid Columns.
     *
     * @return array<int, Column>
     */
    public function columns(): array
    {
        return [
            Column::make('Id', 'id'),
            Column::make('Name', 'name')
                ->sortable()
                ->searchable(),

            Column::make('Email', 'email')
                ->sortable()
                ->searchable(),

            Column::add()
                ->title('In Stock')
                ->field('status')
                ->toggleable(true, 'yes', 'no'),

            Column::make('Created at', 'created_at_formatted', 'created_at')
                ->sortable(),

        ];
    }

    /**
     * PowerGrid Filters.
     *
     * @return array<int, Filter>
     */
    public function filters(): array
    {
        return [
            Filter::inputText('name')->operators(['contains']),
            Filter::inputText('email')->operators(['contains']),
            Filter::datetimepicker('created_at'),
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Actions Method
    |--------------------------------------------------------------------------
    | Enable the method below only if the Routes below are defined in your app.
    |
    */

    /**
     * PowerGrid User Action Buttons.
     *
     * @return array<int, Button>
     */

    /*
    public function actions(): array
    {
       return [
           Button::make('edit', 'Edit')
               ->class('bg-indigo-500 cursor-pointer text-white px-3 py-2.5 m-1 rounded text-sm')
               ->route('user.edit', function(\App\Models\User $model) {
                    return $model->id;
               }),

           Button::make('destroy', 'Delete')
               ->class('bg-red-500 cursor-pointer text-white px-3 py-2 m-1 rounded text-sm')
               ->route('user.destroy', function(\App\Models\User $model) {
                    return $model->id;
               })
               ->method('delete')
        ];
    }
    */

    /*
    |--------------------------------------------------------------------------
    | Actions Rules
    |--------------------------------------------------------------------------
    | Enable the method below to configure Rules for your Table and Action Buttons.
    |
    */

    /**
     * PowerGrid User Action Rules.
     *
     * @return array<int, RuleActions>
     */

    /*
    public function actionRules(): array
    {
       return [

           //Hide button edit for ID 1
            Rule::button('edit')
                ->when(fn($user) => $user->id === 1)
                ->hide(),
        ];
    }
    */
    public function onUpdatedToggleable(string $id, string $field, string $value): void
    {
        User::query()->find($id)->update([
            $field => $value,
        ]);
    }
}


---- UserTable.php ----

**Comment by abhaypithadiya** [comment]
I face the same issue with PgTogglebale and PgFlatpicker.

I installed Alpine with npm using
```
npm install alpinejs
```

and added this in resources/js/app.js
```
import Alpine from 'alpinejs'

window.Alpine = Alpine

import './../../vendor/power-components/livewire-powergrid/dist/powergrid'
import './../../vendor/power-components/livewire-powergrid/dist/powergrid.css'

Alpine.start()
```

Then added  @Vite(['resources/css/app.css', 'resources/js/app.js'])

But it still throws the same error.

**Comment by rosolovsky** [comment]
Everything works fine for me. But I remember that there was such a problem. But I can't remember how I fixed it.
You may need to update NPM packages.
There is my package.json file:

```
{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "autoprefixer": "^10.4.14",
        "axios": "^1.4.0",
        "laravel-vite-plugin": "^0.7.5",
        "postcss": "^8.4.23",
        "tailwindcss": "^3.3.2",
        "vite": "^4.3.5"
    },
    "dependencies": {
        "@tailwindcss/forms": "^0.5.3",
        "alpinejs": "^3.12.0",
        "flatpickr": "^4.6.13",
        "flowbite-datepicker": "^1.2.2",
        "slim-select": "^2.5.0",
        "tom-select": "^2.2.2"
    }
}
```

**Comment by marineusde** [comment]
> Everything works fine for me. But I remember that there was such a problem. But I can't remember how I fixed it. You may need to update NPM packages. There is my package.json file:
> 
> ```
> {
>     "private": true,
>     "scripts": {
>         "dev": "vite",
>         "build": "vite build"
>     },
>     "devDependencies": {
>         "autoprefixer": "^10.4.14",
>         "axios": "^1.4.0",
>         "laravel-vite-plugin": "^0.7.5",
>         "postcss": "^8.4.23",
>         "tailwindcss": "^3.3.2",
>         "vite": "^4.3.5"
>     },
>     "dependencies": {
>         "@tailwindcss/forms": "^0.5.3",
>         "alpinejs": "^3.12.0",
>         "flatpickr": "^4.6.13",
>         "flowbite-datepicker": "^1.2.2",
>         "slim-select": "^2.5.0",
>         "tom-select": "^2.2.2"
>     }
> }
> ```

Same configuration in my project and it works. Maybe you can delete all the files in public/build and run "npm run build" again?

**Comment by zifala-admin** [comment]
what is the solution for this?

**Comment by EricPaulson** [comment]
> what is the solution for this?

In my case, I just needed to update Alpinejs to the latest major version `npm install alpinejs@3.12.0`, and then the errors went away. 

Still can't get toggleable() to work right, but at least the console isn't blowing up now.

**Comment by luanfreitasdev** [comment]
Can you record a video? Are you using Builder or Collection?

**Comment by CrazyBoy49z** [comment]
The problem is in the wrong configuration, read the documentation

https://v4.livewire-powergrid.com/get-started/configure.html
